### ISSUE TITLE
Dark themes?

### ISSUE THREAD

**Issue by KTibow** [mikosoft83/hass-windows10-themes#1]
Windows 10 supports dark mode. It'd be cool if you could make it have a dark background color and a light text color.

**Comment by mikosoft83** [comment]
@KTibow not a very high priority for me as I don't use dark mode on Windows but I did think about it and will probably make it in the future. Thanks for the tip!

**Comment by mikosoft83** [comment]
I guess that's it now :) Thanks  lot for your help especially with the theme generator, that helped immensely.
