### ISSUE TITLE
Auto dark mode

### ISSUE THREAD

**Issue by woutervanoorschot** [mikosoft83/hass-windows10-themes#3]
Homeassistant added support for themes with both dark and light mode in one theme, so the frontend will use whatever theme is requested (by user or by the system default). This means the dark and light themes can be merged, and we don't have to setup theme-changing automations anymore. 

Do you want to support this in the windows 10 themes? The change is basically merging the themes into one file, under a dark- and light key in yaml. More details here: https://www.home-assistant.io/integrations/frontend/#dark-mode-support

Nonetheless these themes are great, thanks for the work put into them.

**Comment by mikosoft83** [comment]
Thanks for the heads up, I completely missed that in the release notes. There is a version 2.0 now out that will support this, so there will be no more dark and light themes, the themes will reflect the selection made in profile. It should be available in HACS shortly.

**Comment by woutervanoorschot** [comment]
Awesome! Thanks for the work!
