### ISSUE TITLE
12.2022 icon state color not working 

### ISSUE THREAD

**Issue by direx1** [mikosoft83/hass-windows10-themes#7]
The active icon state color is no longer working. I'm guessing perhaps the style name changed?
![SmartSelect_20221213_094759_Home Assistant](https://user-images.githubusercontent.com/77240604/207284639-44deefd8-815c-47d7-9264-897e5d9cc1e5.jpg)

**Comment by mikosoft83** [comment]
Hi, yes, it's because HA changed how they handle state colors, there are now some ~30 different colors based on type of entity and it's state
I'm now thinking how to handle this, maybe split the themes to ones that will collapse all colors into the accent color or if I should somehow obey the different colors?
What do you think?

**Comment by direx1** [comment]
After finding a thread on this iv now added the relevant state colors to the theme yaml. Personally I want them to all the the same color regardless of whether it's a switch/boolean/script etc. It maybe an idea to add them all with one color but provide details for others on the respiratory of what to change if they want default ones.

**Comment by ChristophCaina** [comment]
with the recent versions of february, the devs have (finally) implemented officiall supported state color variables for the different domains and device classes available in homeassistant.

these colors can now be individually added into the theme yaml files and changed to personal preferences.

the easiest way would probably to use the 'state-binary_sensor-active-color' to define the specific state icon color.

**Comment by mikosoft83** [comment]
I finally got to it. It's fixed now and should be reflected in HACS in some time.
