### ISSUE TITLE
Not a bug or request, just a question

### ISSUE THREAD

**Issue by JoeGhost-22** [mikosoft83/hass-windows10-themes#8]
Hello, I use your theme and want to add a backgroud image in the theme instead of adding it into every view at the dashboard yaml.
Is it possible to add a background image to your theme and if yes, how? (it would be extremly nice if you can tell me where I need to add what, cause I'm new to all that)

Thank you and have a nice day.
Joerg

**Comment by mikosoft83** [comment]
Hi
If you have card-mod installed (which my themes use quite a lot) you can do it there: https://github.com/thomasloven/lovelace-card-mod/blob/master/README-themes.md
In this example theme you have the background set at line 6: https://github.com/thomasloven/lovelace-card-mod/blob/master/test/themes/airy.yaml
